/* eslint-disable */
// This file is auto-generated by `pnpm guide:build`. Do not edit manually.

export type GuideDocHeading = {
  id: string
  text: string
  level: number
}

export type GuideDocSection = {
  id: string
  filename: string
  title: string
  summary: string
  markdown: string
  isEntry: boolean
  headings: GuideDocHeading[]
}

const assetMap: Record<string, string> = {
  "image-1.png": new URL("../../doc/image-1.png", import.meta.url).href,
  "image-10.png": new URL("../../doc/image-10.png", import.meta.url).href,
  "image-11.png": new URL("../../doc/image-11.png", import.meta.url).href,
  "image-12.png": new URL("../../doc/image-12.png", import.meta.url).href,
  "image-13.png": new URL("../../doc/image-13.png", import.meta.url).href,
  "image-14.png": new URL("../../doc/image-14.png", import.meta.url).href,
  "image-15.png": new URL("../../doc/image-15.png", import.meta.url).href,
  "image-2.png": new URL("../../doc/image-2.png", import.meta.url).href,
  "image-3.png": new URL("../../doc/image-3.png", import.meta.url).href,
  "image-4.png": new URL("../../doc/image-4.png", import.meta.url).href,
  "image-5.png": new URL("../../doc/image-5.png", import.meta.url).href,
  "image-6.png": new URL("../../doc/image-6.png", import.meta.url).href,
  "image-7.png": new URL("../../doc/image-7.png", import.meta.url).href,
  "image-8.png": new URL("../../doc/image-8.png", import.meta.url).href,
  "image-9.png": new URL("../../doc/image-9.png", import.meta.url).href,
  "image.png": new URL("../../doc/image.png", import.meta.url).href,
  "opencode-step-1.png": new URL("../../doc/opencode-step-1.png", import.meta.url).href,
  "opencode-step-2.png": new URL("../../doc/opencode-step-2.png", import.meta.url).href,
  "opencode-step-3.png": new URL("../../doc/opencode-step-3.png", import.meta.url).href,
  "opencode-step-4.png": new URL("../../doc/opencode-step-4.png", import.meta.url).href,
  "opencode-step-5.png": new URL("../../doc/opencode-step-5.png", import.meta.url).href,
  "opencode-step-6.png": new URL("../../doc/opencode-step-6.png", import.meta.url).href,
  "trae-decision-flow.svg": new URL("../../doc/trae-decision-flow.svg", import.meta.url).href,
  "trae-prep-card.svg": new URL("../../doc/trae-prep-card.svg", import.meta.url).href,
  "trae-settings-checklist.svg": new URL("../../doc/trae-settings-checklist.svg", import.meta.url).href,
}

export const guideDocSections: GuideDocSection[] = [
  {
    id: "doc-guide",
    filename: "guide",
    title: "GPAPI 接入总入口",
    summary: "总入口页，负责通用准备、选型建议和统一排错。",
    markdown: `---

## 先看 30 秒版本

接入任何客户端，本质上都只是在填 3 个值：

- \`Base URL\`
- \`API Key\`
- \`Model\`

最常见的正确填写方式是：

\`\`\`text
Provider: OpenAI 或 OpenAI Compatible
Base URL: https://接口域名/v1
API Key: sk-xxxxxxxxxxxxxxxx
Model: 真实模型名
\`\`\`

如果不清楚这 3 个值从哪里来，先看下面这节。

## 一、接入前准备

开始前，至少要准备下面这 3 个信息：

| 项目 | 说明 | 示例 |
| --- | --- | --- |
| \`Base URL\` | 中转接口地址，不是官网首页地址 | \`https://api.example.com/v1\` |
| \`API Key\` | 访问密钥，通常以 \`sk-\` 开头 | \`sk-xxxxxxxxxxxxxxxx\` |
| \`Model\` | 账号实际可用的模型名 | \`gpt-4o\`、\`GPT-5.4\` |

可以先把它理解成：

- \`Base URL\` 决定“请求发到哪里”
- \`API Key\` 决定“请求使用哪把密钥”
- \`Model\` 决定“请求调用哪个模型”

### 一定要记住的 3 句话

1. \`Base URL\` 填接口地址，不要填平台官网地址
2. \`Model\` 要按后台真实模型名填写，不要自己猜
3. 大多数 OpenAI 兼容接口，地址通常要写到 \`/v1\`

### 如果接的是 GPAPI

最短路径通常是：

1. 登录 GPAPI 控制台
2. 打开左侧菜单 \`API 密钥\`
3. 创建或复制 \`API Key\`
4. 在同一页查看或复制 \`API 端点\`
5. 在后台确认当前账号可用的模型

如果其它子教程里要求填写：

- \`API Host\`
- \`Endpoint\`
- \`Server URL\`

本质上大多都还是在填 \`Base URL\`。

## 二、先选需要查看的教程

下面这些是当前已经拆开的子文档。

### 推荐先看哪一篇

| 客户端 | 建议去看 |
| --- | --- |
| Codex / Codex CLI / VS Code Codex | [Codex.md](#doc-codex) |
| Chatbox | [chatbox.md](#doc-chatbox) |
| OpenCode | [OpenCode.md](#doc-opencode) |
| OpenClaw | [OpenClaw.md](#doc-openclaw) |
| Cursor | [Curso.md](#doc-curso) |
| Trae | [Trae.md](#doc-trae) |
| 还没装 Node.js，但教程里要执行 \`npm install\` | [node.js.md](#doc-node-js) |

### 各文档适合什么人

#### 1. Codex / Codex CLI / VS Code Codex

看这里：[Codex.md](#doc-codex)

适合：

- 想把 Codex 全家桶接到同一个中转配置上
- 能接受先改一次 \`~/.codex/config.toml\`
- 想先配通 CLI，再复用到桌面版和 VS Code 扩展

#### 2. Chatbox

看这里：[chatbox.md](#doc-chatbox)

适合：

- 想用图形界面
- 希望尽量通过设置页完成接入
- 想先用 \`Check\` 按钮做最低成本验证

#### 3. OpenCode

看这里：[OpenCode.md](#doc-opencode)

适合：

- 想用本地 CLI 工具
- 能接受写配置文件
- 想要一份已经带示例配置和截图的教程

#### 4. OpenClaw

看这里：[OpenClaw.md](#doc-openclaw)

适合：

- 更喜欢向导式配置
- 想通过 \`Custom Provider\` 接入
- 希望步骤更偏“照着点就行”

#### 5. Cursor

看这里：[Curso.md](#doc-curso)

适合：

- 已经在用 Cursor
- 想先确认当前版本有没有公开的自定义 \`Base URL\` 入口
- 愿意按文档先验证“能不能接”，再决定要不要继续

#### 6. Trae

看这里：[Trae.md](#doc-trae)

适合：

- 已经在用 Trae
- 想确认当前公开版本能不能接第三方 OpenAI 兼容接口
- 更需要一份“能配就配，不能配就及时止损”的教程

#### 7. Node.js

看这里：[node.js.md](#doc-node-js)

如果在其它文档里看到了这些命令：

- \`npm install -g ...\`
- \`node --version\`
- \`npm --version\`

那就先把 Node.js 装好，再继续后面的客户端教程。

## 三、没有单独教程时，先按通用规则填

如果当前接的是：

- VS Code 里的其它插件
- 还没有独立子文档的客户端
- 其它支持 OpenAI 兼容接口的工具

可以先按这套通用规则来：

| 客户端里常见名字 | 应填写内容 |
| --- | --- |
| \`Provider\` | \`OpenAI\` 或 \`OpenAI Compatible\` |
| \`Base URL\` / \`API Host\` / \`Endpoint\` / \`Server URL\` | 中转地址，通常到 \`/v1\` |
| \`API Key\` / \`Access Token\` / \`Secret Key\` | \`API Key\` |
| \`Model\` / \`Model Name\` / \`Chat Model\` | 真实模型名 |
| \`Organization\` / \`Project\` | 一般留空，除非客户端强制要求 |

### 通用复制模板

\`\`\`text
Provider: OpenAI Compatible
Base URL: https://api.example.com/v1
API Key: sk-xxxxxxxxxxxxxxxx
Model: gpt-4o
\`\`\`

### 最常见的 3 个填写错误

1. 把 \`Base URL\` 错填成平台官网地址
2. 把展示名称当成真实模型名
3. 在地址里重复拼接 \`/v1/chat/completions\`

## 四、怎么判断自己该看哪篇

如果还在犹豫，可以直接按下面选择：

- 想最快接起来：先看 [OpenClaw.md](#doc-openclaw)
- 想用 Codex 全家桶：看 [Codex.md](#doc-codex)
- 想用图形界面快速测试：看 [chatbox.md](#doc-chatbox)
- 想用 CLI、能接受配文件：先看 [OpenCode.md](#doc-opencode)
- 已经在用 Cursor：看 [Curso.md](#doc-curso)
- 已经在用 Trae：看 [Trae.md](#doc-trae)
- 被 \`npm\` / \`node\` 卡住：先看 [node.js.md](#doc-node-js)

## 五、统一排错说明

不管接的是哪个客户端，失败时先按这个顺序检查。

### 1. 先查地址

- 填写的是中转接口地址，不是官网首页
- 地址通常建议写到 \`/v1\`
- 不要在多个输入框里重复拼接接口路径

### 2. 再查 Key

- 确认没有多复制空格和换行
- 确认该 Key 没有被禁用
- 确认该 Key 还有额度或权限

### 3. 再查模型名

- 必须和后台开放名称完全一致
- 注意大小写、连字符、版本号
- 优先复制后台原文，不要手改

### 4. 再查客户端模式

- 优先选择 \`OpenAI\` 或 \`OpenAI Compatible\`
- 如果客户端支持多个 Provider，确认当前真的切到了刚配置的那个
- 如果客户端区分聊天、补全、嵌入，请先只测试聊天能力

### 5. 最后查服务端

- 域名是否能访问
- 证书是否正常
- 反向代理是否配置正确

### 常见报错速查

| 报错或现象 | 优先排查项 |
| --- | --- |
| \`401 Unauthorized\` | \`API Key\` 是否正确、是否复制了空格 |
| \`404\` 或接口不存在 | \`Base URL\` 是否写错、是否重复拼路径 |
| 模型不存在 | 模型名是否是真实可用名称 |
| 能连上但回复失败 | 当前 Key 是否有该模型权限 |
| 保存后没反应 | 客户端是否仍在使用旧配置、是否需要重启 |

## 六、推荐阅读顺序

如果是第一次接触这类接入，推荐按这个顺序阅读：

1. 先读这篇 \`guide.md\`
2. 如果需要安装运行环境，先读 [node.js.md](#doc-node-js)
3. 再读对应客户端的子教程
4. 接入失败时，再回到这篇文档看“统一排错说明”

## 七、这篇主文档以后怎么维护

为了避免一处改了、另一处忘了改，后面建议这样维护：

- \`guide.md\` 只放总入口、通用规则、统一排错
- 每个客户端的实际步骤，单独维护在自己的子文档里
- 客户端截图、特殊限制、版本差异，也只写在对应子文档里

这样做的好处是：

1. 主文档更短，更适合新手先快速判断方向
2. 子文档可以按客户端单独更新，不容易互相影响
3. 遇到像 Trae 这种“公开支持路径不稳定”的情况，也能单独说明，不会把主文档写乱`,
    isEntry: true,
    headings: [
      {
        "id": "doc-guide-先看-30-秒版本",
        "text": "先看 30 秒版本",
        "level": 2
      },
      {
        "id": "doc-guide-一-接入前准备",
        "text": "一、接入前准备",
        "level": 2
      },
      {
        "id": "doc-guide-一定要记住的-3-句话",
        "text": "一定要记住的 3 句话",
        "level": 3
      },
      {
        "id": "doc-guide-如果接的是-gpapi",
        "text": "如果接的是 GPAPI",
        "level": 3
      },
      {
        "id": "doc-guide-二-先选需要查看的教程",
        "text": "二、先选需要查看的教程",
        "level": 2
      },
      {
        "id": "doc-guide-推荐先看哪一篇",
        "text": "推荐先看哪一篇",
        "level": 3
      },
      {
        "id": "doc-guide-各文档适合什么人",
        "text": "各文档适合什么人",
        "level": 3
      },
      {
        "id": "doc-guide-三-没有单独教程时-先按通用规则填",
        "text": "三、没有单独教程时，先按通用规则填",
        "level": 2
      },
      {
        "id": "doc-guide-通用复制模板",
        "text": "通用复制模板",
        "level": 3
      },
      {
        "id": "doc-guide-最常见的-3-个填写错误",
        "text": "最常见的 3 个填写错误",
        "level": 3
      },
      {
        "id": "doc-guide-四-怎么判断自己该看哪篇",
        "text": "四、怎么判断自己该看哪篇",
        "level": 2
      },
      {
        "id": "doc-guide-五-统一排错说明",
        "text": "五、统一排错说明",
        "level": 2
      },
      {
        "id": "doc-guide-1-先查地址",
        "text": "1. 先查地址",
        "level": 3
      },
      {
        "id": "doc-guide-2-再查-key",
        "text": "2. 再查 Key",
        "level": 3
      },
      {
        "id": "doc-guide-3-再查模型名",
        "text": "3. 再查模型名",
        "level": 3
      },
      {
        "id": "doc-guide-4-再查客户端模式",
        "text": "4. 再查客户端模式",
        "level": 3
      },
      {
        "id": "doc-guide-5-最后查服务端",
        "text": "5. 最后查服务端",
        "level": 3
      },
      {
        "id": "doc-guide-常见报错速查",
        "text": "常见报错速查",
        "level": 3
      },
      {
        "id": "doc-guide-六-推荐阅读顺序",
        "text": "六、推荐阅读顺序",
        "level": 2
      },
      {
        "id": "doc-guide-七-这篇主文档以后怎么维护",
        "text": "七、这篇主文档以后怎么维护",
        "level": 2
      }
    ],
  },
  {
    id: "doc-codex",
    filename: "Codex",
    title: "Codex 接入中转站 API 教程",
    summary: "覆盖 Codex app、Codex CLI 与 VS Code Codex 的统一接入方案。",
    markdown: `这篇文档把 3 种用法写在一起：

1. \`Codex\` 桌面版
2. \`Codex CLI\`
3. \`VS Code Codex\`

先看一个最重要的结论：

\`Codex CLI\`、\`VS Code Codex\`，以及 Codex app 里的大部分本地 agent 配置，核心都围绕同一个配置文件：

\`\`\`text
~/.codex/config.toml
\`\`\`

最省事的方式不是 3 个地方分别配置 3 次，而是：

1. 先把 \`Codex CLI\` 配通
2. 再让桌面版和 VS Code Codex 复用这套配置

## 开始前先准备这 3 个值

- \`Base URL\`：\`https://token.gepinkeji.com/v1\`
- \`API Key\`：接口密钥，例如 \`sk-xxxx\`
- \`Model\`：建议先用 \`GPT-5.4\`

如果中转站已经明确给出其它模型名，以后台真实模型名为准。

### 如果不清楚真实模型名的获取位置

最短路径先按这个顺序找：

1. 登录中转站后台
2. 找 \`模型列表\`、\`允许模型\`、\`可用模型\`、\`接口文档\`
3. 复制其中真正用于请求的 \`model id\`

需要区分两种名字：

- 展示名称：给人看的，例如“GPT-5.4 高级版”
- 真实模型名：给客户端填的，例如 \`GPT-5.4\`

如果后台没有模型列表，直接查看接口文档或联系支持，不建议猜测模型名。

## 官方链接

- Codex 官方文档：https://developers.openai.com/codex/
- Codex CLI：https://developers.openai.com/codex/cli
- Codex Authentication：https://developers.openai.com/codex/auth
- Codex IDE Extension：https://developers.openai.com/codex/ide
- Codex IDE Settings：https://developers.openai.com/codex/ide/settings
- Codex App：https://developers.openai.com/codex/app
- Node.js 教程：[node.js.md](#doc-node-js)

## 先理解这篇教程的配置思路

Codex 官方文档明确支持：

- 用 API Key 登录
- 用 \`~/.codex/config.toml\` 配模型和 provider
- CLI 与 IDE 扩展共享同一套登录与配置思路

但官方文档主要是围绕 OpenAI 自己的 API 与账号体系写的。

本文的目标是把这套配置结构改成指向中转站的 OpenAI 兼容地址。

这也是本文优先采用下面顺序的原因：

1. 先把 \`Codex CLI\` 配好
2. 再复用到 Codex app 和 VS Code Codex

## 第 1 步：如果还没安装 Node.js，先安装 Node.js

如果执行下面命令会报错：

\`\`\`bash
node --version
npm --version
\`\`\`

那就先去看：

- [node.js.md](#doc-node-js)

确认 \`node --version\` 和 \`npm --version\` 都能正常显示版本号后，再继续下面的步骤。

## 第 2 步：安装 Codex CLI

打开终端，执行：

\`\`\`bash
npm install -g @openai/codex
\`\`\`

安装完成后，执行：

\`\`\`bash
codex --version
\`\`\`

如果能正常显示版本号，说明 \`Codex CLI\` 已经装好了。

## 第 3 步：先用 API Key 登录

最简单的做法是直接把 Key 通过 stdin 交给 Codex：

\`\`\`bash
printf 'sk-请替换成真实密钥' | codex login --with-api-key
\`\`\`

登录完成后，再执行：

\`\`\`bash
codex login status
\`\`\`

如果看到类似“Logged in using an API key”的结果，说明登录已经成功。

### 这一步要注意什么

1. 这里填的是中转站 \`API Key\`
2. 不要多复制空格和换行
3. 如果之前已经登录过别的 Key，可以重新执行一次覆盖

## 第 4 步：编辑 \`~/.codex/config.toml\`

这是整篇文档最关键的一步。

打开：

\`\`\`text
~/.codex/config.toml
\`\`\`

如果文件不存在，就手动创建。

第一次接入，最省事的写法可以直接参考下面这份：

\`\`\`toml
model_provider = "gpapi"
model = "gpt-5.4"
review_model = "gpt-5.4"

[model_providers.gpapi]
name = "GPAPI"
base_url = "https://token.gepinkeji.com/v1"
wire_api = "responses"
requires_openai_auth = true
\`\`\`

### 这几行分别是什么意思

- \`model_provider = "gpapi"\`
  说明默认走这里定义的 provider
- \`model = "gpt-5.4"\`
  说明默认使用这个模型
- \`review_model = "gpt-5.4"\`
  说明代码评审等场景也先走这个模型
- \`base_url\`
  指向中转地址
- \`wire_api = "responses"\`
  这是当前 Codex 配置里更稳妥的写法
- \`requires_openai_auth = true\`
  让这个 provider 继续使用前面 \`codex login\` 缓存下来的认证

### 最容易误解的两行

#### 1. \`requires_openai_auth = true\` 到底是什么意思

这里不是要求再次登录新的 OpenAI 账号。

可以直接理解成：

\`继续使用执行 codex login --with-api-key 之后，本地已经缓存下来的那份认证。\`

也就是说：

1. 前面那条 \`codex login --with-api-key\` 会产出可复用的认证
2. 这里会继续使用那次登录得到的认证头
3. 可以把它理解成“继续沿用前面录入的 Key 所生成的认证”

#### 2. \`wire_api = "responses"\` 为什么这样写

这是当前 Codex 配置里更稳的写法，而且当前版本已经不再推荐旧的 \`chat\` 写法。

如果这里报错，不建议立刻改成别的值，优先检查：

1. \`base_url\` 是否正确
2. 中转站是否真的兼容当前 Codex 所走的接口
3. \`model\` 是否是真实可用模型名

### 如果需要更换模型

只需要把：

\`\`\`toml
model = "gpt-5.4"
review_model = "gpt-5.4"
\`\`\`

改成真实模型名，例如：

\`\`\`toml
model = "gpt-5.3-codex"
review_model = "gpt-5.3-codex"
\`\`\`

前提是中转站后台确实支持这个模型。

## 第 5 步：先用 Codex CLI 做最短验证

进入任意一个测试目录，执行：

\`\`\`bash
codex
\`\`\`

然后给它发一句最简单的话：

\`\`\`text
请只回复：Codex CLI 已连接成功
\`\`\`

如果能正常回复，说明下面这整套链路至少已经通了：

- 登录
- \`config.toml\`
- \`Base URL\`
- \`API Key\`
- \`Model\`

### 如果 CLI 还没通，先不要急着配置另外两个

因为：

- Codex app
- VS Code Codex

后面基本都建立在这套配置之上。

最稳的顺序如下：

1. 先通 CLI
2. 再去看桌面版
3. 最后看 VS Code 扩展

### 如果 CLI 失败，先按这个顺序排查

#### 情况 1：\`codex login status\` 就不正常

先重做：

\`\`\`bash
printf 'sk-请替换成真实密钥' | codex login --with-api-key
\`\`\`

然后再执行：

\`\`\`bash
codex login status
\`\`\`

#### 情况 2：登录正常，但一发消息就报错

先检查：

1. \`~/.codex/config.toml\` 是否已经保存
2. \`base_url\` 是否写成了完整接口地址
3. \`model_provider\` 是否真的写成了 \`gpapi\`
4. \`model\` 是否是真实模型名

#### 情况 3：提示 401 或鉴权失败

优先检查：

1. 登录时使用的是否是当前这把 Key
2. Key 有没有多复制空格或换行
3. 这把 Key 在后台是否还启用

#### 情况 4：提示 404、接口不存在、unknown endpoint

优先检查：

1. \`base_url\` 是否写错
2. 地址里有没有重复拼路径
3. 中转站是否兼容 Codex 当前走的接口格式

#### 情况 5：提示模型不存在

优先检查：

1. 填写的是否是展示名称
2. 当前 Key 是否有这个模型权限
3. 模型名大小写、连接符、版本号是否抄错

---

## 一、Codex 桌面版怎么用

### 第 1 步：打开 Codex app

如果还没安装桌面版，可以先执行：

\`\`\`bash
codex app
\`\`\`

或者直接从 Codex 官方入口打开桌面版。

### 第 2 步：如果 app 需要登录，优先继续用 API Key 方式

如果目标是把本地工作区接到中转站，最简单的方式仍然是：

1. 先用上面那套 \`codex login --with-api-key\`
2. 再让 app 读取同一套认证和配置

如果前面已经把 CLI 配通，最稳的动作如下：

1. 先完全退出 Codex app
2. 确认 \`~/.codex/config.toml\` 已经保存
3. 再重新打开 app

这样更容易让 app 读到最新配置。

### 第 3 步：确认 app 走的是刚才的配置

进入 app 后，重点确认两件事：

1. 当前打开的是本地工作区，而不是云端任务
2. 当前 agent 使用的是 \`~/.codex/config.toml\` 里配置的模型/provider

最简单的测试方式：

在本地项目里让它回复：

\`\`\`text
请只回复：Codex App 已连接成功
\`\`\`

### 这一步的实话提醒

如果使用的是 Codex Cloud 或依赖 ChatGPT 账户套餐的那套能力，不要把本文的“中转 API 接入”思路和 ChatGPT 账号计费思路混在一起。

最简单的理解方式如下：

- 本文主要覆盖“本地工作区 + API Key + 自定义 provider”
- 如果目标是使用 ChatGPT 套餐内置额度，则按官方账号体系处理

---

## 二、Codex CLI 怎么用

如果前面的验证已经成功，\`Codex CLI\` 实际上已经可以直接使用。

最常见的两种方式：

### 方式 A：直接进入交互模式

\`\`\`bash
codex
\`\`\`

### 方式 B：在当前项目目录里直接提需求

\`\`\`bash
codex "请检查这个项目里有没有明显的接口配置问题"
\`\`\`

### CLI 场景最常见的 3 个坑

1. 只登录了 API Key，但没有改 \`config.toml\`
2. \`base_url\` 写成官网首页地址，而不是接口地址
3. \`wire_api\` 不是 \`responses\`

---

## 三、VS Code Codex 怎么用

### 第 1 步：安装 VS Code Codex 扩展

在 VS Code 里打开扩展市场，搜索并安装官方 Codex 扩展。

### 第 2 步：优先复用前面已经配好的 CLI 配置

对小白来说，最稳的方式不是在 VS Code 里重新配一遍，而是直接复用这两样：

1. \`codex login\` 已经缓存好的登录状态
2. \`~/.codex/config.toml\`

如果前面的 \`Codex CLI\` 已经通了，VS Code Codex 通常也更容易一起通。

第一次接入时，建议按下面顺序处理：

1. 先完全退出 VS Code
2. 确认 \`~/.codex/config.toml\` 已经保存
3. 再重新打开 VS Code
4. 然后再打开 Codex 扩展去测试

### 第 3 步：在 VS Code 里做最小测试

打开一个项目后，唤起 Codex 扩展，然后发送：

\`\`\`text
请只回复：VS Code Codex 已连接成功
\`\`\`

如果可以正常回复，说明这套共享配置已经被扩展吃到了。

### 如果 VS Code 扩展没通，但 CLI 已经通了

先按这个顺序查：

1. VS Code 是否已经完全重启
2. 扩展是不是读取了当前用户下的 \`~/.codex/config.toml\`
3. 当前 VS Code 登录态是不是还是旧配置
4. 扩展当前使用的 provider/model 是否还是默认值

---

## 常见问题

### 1. 为什么这篇文档先讲 CLI，不先讲桌面版

因为 CLI 最容易验证。

只要 CLI 通了，后面的桌面版和 VS Code 扩展通常都更好判断问题出在哪。

### 2. 为什么已经登录成功了，还是调不通

因为“登录成功”只代表本地已经缓存了 Key。

它不代表：

- \`Base URL\` 已经写对
- \`model_provider\` 已经切到中转 provider
- \`model\` 已经写成可用模型名

### 3. \`Base URL\` 要不要写 \`/v1\`

大多数 OpenAI 兼容接口都建议写到 \`/v1\`。

如果后台已经给了完整地址，就以后台显示为准。

### 4. Codex CLI 提示接口错误，先查什么

先查这 4 项：

1. \`codex login status\` 是否正常
2. \`~/.codex/config.toml\` 是否已经保存
3. \`base_url\` 是否正确
4. \`model\` 是否是真实可用模型名

### 5. 哪一种方式更适合首次接入

推荐顺序：

1. 先配 \`Codex CLI\`
2. 再试 \`VS Code Codex\`
3. 最后再看 \`Codex\` 桌面版

这是最稳、最不容易迷路的顺序。`,
    isEntry: false,
    headings: [
      {
        "id": "doc-codex-开始前先准备这-3-个值",
        "text": "开始前先准备这 3 个值",
        "level": 2
      },
      {
        "id": "doc-codex-如果不清楚真实模型名的获取位置",
        "text": "如果不清楚真实模型名的获取位置",
        "level": 3
      },
      {
        "id": "doc-codex-官方链接",
        "text": "官方链接",
        "level": 2
      },
      {
        "id": "doc-codex-先理解这篇教程的配置思路",
        "text": "先理解这篇教程的配置思路",
        "level": 2
      },
      {
        "id": "doc-codex-第-1-步-如果还没安装-node-js-先安装-node-js",
        "text": "第 1 步：如果还没安装 Node.js，先安装 Node.js",
        "level": 2
      },
      {
        "id": "doc-codex-第-2-步-安装-codex-cli",
        "text": "第 2 步：安装 Codex CLI",
        "level": 2
      },
      {
        "id": "doc-codex-第-3-步-先用-api-key-登录",
        "text": "第 3 步：先用 API Key 登录",
        "level": 2
      },
      {
        "id": "doc-codex-这一步要注意什么",
        "text": "这一步要注意什么",
        "level": 3
      },
      {
        "id": "doc-codex-第-4-步-编辑-codex-config-toml",
        "text": "第 4 步：编辑 `~/.codex/config.toml`",
        "level": 2
      },
      {
        "id": "doc-codex-这几行分别是什么意思",
        "text": "这几行分别是什么意思",
        "level": 3
      },
      {
        "id": "doc-codex-最容易误解的两行",
        "text": "最容易误解的两行",
        "level": 3
      },
      {
        "id": "doc-codex-如果需要更换模型",
        "text": "如果需要更换模型",
        "level": 3
      },
      {
        "id": "doc-codex-第-5-步-先用-codex-cli-做最短验证",
        "text": "第 5 步：先用 Codex CLI 做最短验证",
        "level": 2
      },
      {
        "id": "doc-codex-如果-cli-还没通-先不要急着配置另外两个",
        "text": "如果 CLI 还没通，先不要急着配置另外两个",
        "level": 3
      },
      {
        "id": "doc-codex-如果-cli-失败-先按这个顺序排查",
        "text": "如果 CLI 失败，先按这个顺序排查",
        "level": 3
      },
      {
        "id": "doc-codex-一-codex-桌面版怎么用",
        "text": "一、Codex 桌面版怎么用",
        "level": 2
      },
      {
        "id": "doc-codex-第-1-步-打开-codex-app",
        "text": "第 1 步：打开 Codex app",
        "level": 3
      },
      {
        "id": "doc-codex-第-2-步-如果-app-需要登录-优先继续用-api-key-方式",
        "text": "第 2 步：如果 app 需要登录，优先继续用 API Key 方式",
        "level": 3
      },
      {
        "id": "doc-codex-第-3-步-确认-app-走的是刚才的配置",
        "text": "第 3 步：确认 app 走的是刚才的配置",
        "level": 3
      },
      {
        "id": "doc-codex-这一步的实话提醒",
        "text": "这一步的实话提醒",
        "level": 3
      },
      {
        "id": "doc-codex-二-codex-cli-怎么用",
        "text": "二、Codex CLI 怎么用",
        "level": 2
      },
      {
        "id": "doc-codex-方式-a-直接进入交互模式",
        "text": "方式 A：直接进入交互模式",
        "level": 3
      },
      {
        "id": "doc-codex-方式-b-在当前项目目录里直接提需求",
        "text": "方式 B：在当前项目目录里直接提需求",
        "level": 3
      },
      {
        "id": "doc-codex-cli-场景最常见的-3-个坑",
        "text": "CLI 场景最常见的 3 个坑",
        "level": 3
      },
      {
        "id": "doc-codex-三-vs-code-codex-怎么用",
        "text": "三、VS Code Codex 怎么用",
        "level": 2
      },
      {
        "id": "doc-codex-第-1-步-安装-vs-code-codex-扩展",
        "text": "第 1 步：安装 VS Code Codex 扩展",
        "level": 3
      },
      {
        "id": "doc-codex-第-2-步-优先复用前面已经配好的-cli-配置",
        "text": "第 2 步：优先复用前面已经配好的 CLI 配置",
        "level": 3
      },
      {
        "id": "doc-codex-第-3-步-在-vs-code-里做最小测试",
        "text": "第 3 步：在 VS Code 里做最小测试",
        "level": 3
      },
      {
        "id": "doc-codex-如果-vs-code-扩展没通-但-cli-已经通了",
        "text": "如果 VS Code 扩展没通，但 CLI 已经通了",
        "level": 3
      },
      {
        "id": "doc-codex-常见问题",
        "text": "常见问题",
        "level": 2
      },
      {
        "id": "doc-codex-1-为什么这篇文档先讲-cli-不先讲桌面版",
        "text": "1. 为什么这篇文档先讲 CLI，不先讲桌面版",
        "level": 3
      },
      {
        "id": "doc-codex-2-为什么已经登录成功了-还是调不通",
        "text": "2. 为什么已经登录成功了，还是调不通",
        "level": 3
      },
      {
        "id": "doc-codex-3-base-url-要不要写-v1",
        "text": "3. `Base URL` 要不要写 `/v1`",
        "level": 3
      },
      {
        "id": "doc-codex-4-codex-cli-提示接口错误-先查什么",
        "text": "4. Codex CLI 提示接口错误，先查什么",
        "level": 3
      },
      {
        "id": "doc-codex-5-哪一种方式更适合首次接入",
        "text": "5. 哪一种方式更适合首次接入",
        "level": 3
      }
    ],
  },
  {
    id: "doc-chatbox",
    filename: "chatbox",
    title: "Chatbox 接入中转站 API 教程",
    summary: "覆盖 Chatbox 图形界面里的 OpenAI 兼容接入流程。",
    markdown: `适合下面这些场景：

- 不想折腾命令行
- 想用图形界面聊天
- 想尽量少改配置

Chatbox 通常是比较适合首次接入的一种方式。

因为它本身就支持：

- 自定义模型服务商
- OpenAI API compatible
- 手动填写 \`API Host\`、\`API Key\`、\`Model\`

## 开始前先准备这 3 个值

- \`Base URL / API Host\`：\`https://token.gepinkeji.com/v1\`
- \`API Key\`：接口密钥，例如 \`sk-xxxx\`
- \`Model\`：建议先用 \`GPT-5.4\`

先提醒一句：

Chatbox 界面里有时叫：

- \`API Host\`
- \`API Base URL\`
- \`API 地址\`

它本质上大多都在指这里的 \`Base URL\`。

### 如果不清楚真实模型名的获取位置

最短路径先按这个顺序找：

1. 登录中转站后台
2. 找 \`模型列表\`、\`允许模型\`、\`可用模型\`
3. 复制真正用于请求的 \`model id\`

如果后台只给了展示名称，没有给真实模型名，不建议猜测。

## 官方链接

- Chatbox 官网：https://chatboxai.app/
- Chatbox 下载页：https://chatboxai.app/zh
- Chatbox Provider 文档：https://docs.chatboxai.app/en/guides/providers

## 第 1 步：安装并打开 Chatbox

先安装 Chatbox 客户端。

打开后，不要急着开始聊天，先去设置页。

按照 Chatbox 官方文档的常见路径，优先这样找：

1. 打开 Chatbox
2. 点击左下角 \`Settings\`
3. 进入 \`Model Provider\`

如果当前界面是中文，也可能看到：

- \`设置\`
- \`模型服务商\`

## 第 2 步：新增一个自定义 Provider

进入 \`Model Provider\` 后，按这个顺序走：

1. 点击 \`Add\`
2. 给这个 provider 起一个名字，比如 \`GPAPI\`
3. 类型选择 \`OpenAI API compatible\`

如果当前版本没有看到完全一样的文字，就找这些接近的选项：

- \`OpenAI\`
- \`OpenAI API\`
- \`OpenAI Compatible\`
- \`OpenAI API compatible\`

## 第 3 步：填写 API 信息

这一步直接按下面填：

| 字段 | 建议填写 |
| --- | --- |
| Provider Name | \`GPAPI\` |
| API Host | \`https://token.gepinkeji.com/v1\` |
| API Key | 真实密钥 |
| Model | \`GPT-5.4\` |

### 最容易卡住的一点

有些版本会把“路径”单独拆开。

这时可以先这样理解：

- 如果它只让填写 \`API Host\`，优先直接填完整的 \`https://token.gepinkeji.com/v1\`
- 如果它已经默认拼 \`/v1/chat/completions\`，不要再额外重复拼一遍

### 两种最常见界面怎么填

#### 情况 1：只有一个 \`API Host\` 输入框

直接填：

\`\`\`text
https://token.gepinkeji.com/v1
\`\`\`

#### 情况 2：\`Host\` 和 \`Path\` 分成两个框

可以先按这个思路填：

\`\`\`text
Host:
https://token.gepinkeji.com

Path:
/v1
\`\`\`

如果当前版本已经在内部固定拼了 \`/v1/chat/completions\`，不要再把完整路径重复塞进 \`Host\`。

## 第 4 步：至少新增 1 个模型

按 Chatbox 官方文档的通用配置流程，保存前一般要至少加 1 个模型。

所以如果界面里有“添加模型”这一步，请至少加一个：

\`\`\`text
GPT-5.4
\`\`\`

如果中转后台给出的真实模型名不是这个，就以后台为准。

## 第 5 步：点击 Check 做第一次验证

保存前后，Chatbox 常见都会有一个：

\`\`\`text
Check
\`\`\`

或者：

\`\`\`text
检查连接
\`\`\`

的按钮。

先点击这个按钮。

如果显示连接成功，说明下面这些值至少已经基本没填错：

- \`API Host\`
- \`API Key\`
- \`Model\`

## 第 6 步：回到首页发一条最简单的测试消息

创建一个新对话，然后直接发：

\`\`\`text
请只回复：Chatbox 已连接成功
\`\`\`

如果能正常回复，说明 Chatbox 已经接通。

### 如果 \`Check\` 失败，先按这个顺序看

#### 1. 提示 401 或鉴权失败

优先查：

1. \`API Key\` 是否完整
2. 是否多复制了空格
3. 这把 Key 是否启用

#### 2. 提示 404 或接口不存在

优先查：

1. \`API Host\` 是否写错
2. 是否重复拼了 \`/v1\` 或 \`/chat/completions\`
3. \`Host\` 和 \`Path\` 是否填反了

#### 3. 提示模型不存在

优先查：

1. 填写的是不是展示名称
2. 当前模型名是否和后台完全一致
3. 当前 Key 是否有这个模型权限

## 常见问题

### 1. 为什么地址已经填写，还是连不上

最常见的原因是：

1. 官网地址被填进去了
2. 少写了 \`/v1\`
3. 两个地方重复拼了接口路径

### 2. 为什么 Check 能过，但聊天还是不对

优先查这 3 个地方：

1. 当前对话是不是已经切到了刚添加的 provider
2. 当前模型是不是刚填写的模型
3. Chatbox 有没有缓存旧配置

如果怀疑缓存了旧配置，最简单的处理方式如下：

1. 关闭 Chatbox
2. 重新打开
3. 新建一个全新的聊天窗口再测

### 3. 模型不存在怎么办

优先检查：

1. 是不是把展示名称当成真实模型名了
2. 这个 Key 当前有没有这个模型权限
3. 模型名大小写、连接符、版本号有没有抄错

### 4. API Key 正确，为什么还提示无权限

这时不要先怀疑 Chatbox，先回到中转站后台看：

- Key 是否启用
- Key 是否还有额度
- Key 是否已分组
- 当前分组是否允许这个模型

### 5. Chatbox 最适合怎么接

最推荐的小白顺序是：

1. 先新增一个 \`OpenAI API compatible\` provider
2. 先只填一组最简单配置
3. 先点 \`Check\`
4. 再开新对话测试

不要一上来就同时开多个 provider、多组模型、多套高级参数。`,
    isEntry: false,
    headings: [
      {
        "id": "doc-chatbox-开始前先准备这-3-个值",
        "text": "开始前先准备这 3 个值",
        "level": 2
      },
      {
        "id": "doc-chatbox-如果不清楚真实模型名的获取位置",
        "text": "如果不清楚真实模型名的获取位置",
        "level": 3
      },
      {
        "id": "doc-chatbox-官方链接",
        "text": "官方链接",
        "level": 2
      },
      {
        "id": "doc-chatbox-第-1-步-安装并打开-chatbox",
        "text": "第 1 步：安装并打开 Chatbox",
        "level": 2
      },
      {
        "id": "doc-chatbox-第-2-步-新增一个自定义-provider",
        "text": "第 2 步：新增一个自定义 Provider",
        "level": 2
      },
      {
        "id": "doc-chatbox-第-3-步-填写-api-信息",
        "text": "第 3 步：填写 API 信息",
        "level": 2
      },
      {
        "id": "doc-chatbox-最容易卡住的一点",
        "text": "最容易卡住的一点",
        "level": 3
      },
      {
        "id": "doc-chatbox-两种最常见界面怎么填",
        "text": "两种最常见界面怎么填",
        "level": 3
      },
      {
        "id": "doc-chatbox-第-4-步-至少新增-1-个模型",
        "text": "第 4 步：至少新增 1 个模型",
        "level": 2
      },
      {
        "id": "doc-chatbox-第-5-步-点击-check-做第一次验证",
        "text": "第 5 步：点击 Check 做第一次验证",
        "level": 2
      },
      {
        "id": "doc-chatbox-第-6-步-回到首页发一条最简单的测试消息",
        "text": "第 6 步：回到首页发一条最简单的测试消息",
        "level": 2
      },
      {
        "id": "doc-chatbox-如果-check-失败-先按这个顺序看",
        "text": "如果 `Check` 失败，先按这个顺序看",
        "level": 3
      },
      {
        "id": "doc-chatbox-常见问题",
        "text": "常见问题",
        "level": 2
      },
      {
        "id": "doc-chatbox-1-为什么地址已经填写-还是连不上",
        "text": "1. 为什么地址已经填写，还是连不上",
        "level": 3
      },
      {
        "id": "doc-chatbox-2-为什么-check-能过-但聊天还是不对",
        "text": "2. 为什么 Check 能过，但聊天还是不对",
        "level": 3
      },
      {
        "id": "doc-chatbox-3-模型不存在怎么办",
        "text": "3. 模型不存在怎么办",
        "level": 3
      },
      {
        "id": "doc-chatbox-4-api-key-正确-为什么还提示无权限",
        "text": "4. API Key 正确，为什么还提示无权限",
        "level": 3
      },
      {
        "id": "doc-chatbox-5-chatbox-最适合怎么接",
        "text": "5. Chatbox 最适合怎么接",
        "level": 3
      }
    ],
  },
  {
    id: "doc-opencode",
    filename: "OpenCode",
    title: "OpenCode 接入 OpenAI 兼容 API 教程",
    summary: "覆盖 OpenCode 的安装、配置文件和 `/connect` 接入方式。",
    markdown: `这篇文档参考了腾讯云这篇文章的操作顺序：

- 参考文章：https://cloud.tencent.com/developer/article/2624487

但这里已经按你的实际接入信息重新整理成可直接使用的版本：

- 网关地址：\`https://token.gepinkeji.com/v1\`
- 示例模型：\`GPT-5.4\`

## 官方网站

- OpenCode 官网：https://opencode.ai/
- OpenCode 文档：https://opencode.ai/docs/
- OpenCode Providers 文档：https://opencode.ai/docs/providers
- Node.js 教程：[node.js.md](#doc-node-js)

## 开始前你要准备什么

你只需要准备 3 个信息：

- \`Base URL\`：\`https://token.gepinkeji.com/v1\`
- \`API Key\`：你的接口密钥，例如 \`sk-xxxx\`
- \`Model\`：\`GPT-5.4\`

如果你还没有安装 Node.js，请先完成这里的步骤：

- [Node.js 安装教程](#doc-node-js)

安装完成后，先在终端里执行：

\`\`\`bash
node --version
npm --version
\`\`\`

如果这两条命令都能正常返回版本号，再继续下面的 OpenCode 安装。

---

## 步骤 1：安装 OpenCode

打开终端，执行：

\`\`\`bash
npm install -g opencode-ai
\`\`\`

安装完成后执行：

\`\`\`bash
opencode --version
\`\`\`

如果能正常显示版本号，说明 OpenCode 已经装好了。

![OpenCode 安装截图](${assetMap["opencode-step-1.png"]})

---

## 步骤 2：配置你的 OpenAI 兼容接口

### 2.1 配置文件放在哪里

你可以二选一：

1. 放在当前项目根目录，文件名叫 \`opencode.json\`
2. 放到全局目录：\`~/.config/opencode/opencode.json\`

也可以使用：

- \`opencode.jsonc\`

如果这些文件或目录不存在，就手动创建。

如果你是第一次接触 OpenCode，建议直接放在项目根目录，这样最不容易找错位置。

### 2.2 先理解 provider 的用法

OpenCode 可以使用：

1. 默认 provider，例如 \`openai\` / \`anthropic\` / \`google\`
2. 自定义 provider_id，例如你自己起一个名字

你这次给的是默认 \`openai\` provider 的完整配置方式，所以文档下面直接按这个结构来写。

API Key 也有两种用法：

1. 直接写进配置文件
2. 启动 OpenCode 后通过 \`/connect\` 命令配置

如果你只是本机自己使用，直接写进配置文件最省事。  
如果你不想把 Key 明文写进文件，就保留空配置后用 \`/connect\` 录入。

### 2.3 配置 \`opencode.json\` 或 \`opencode.jsonc\`

先创建配置文件，内容可以直接参考下面这份。

说明：

- 我已经把你的网关地址改成文档可直接使用的值

\`\`\`json
{
  "provider": {
    "openai": {
      "options": {
        "baseURL": "https://token.gepinkeji.com/v1",
        "apiKey": "sk-请替换成你自己的真实APIKey"
      },
      "models": {
        "gpt-5-codex": {
          "name": "GPT-5 Codex",
          "limit": {
            "context": 400000,
            "output": 128000
          },
          "options": {
            "store": false
          },
          "variants": {
            "low": {},
            "medium": {},
            "high": {}
          }
        },
        "gpt-5.1-codex": {
          "name": "GPT-5.1 Codex",
          "limit": {
            "context": 400000,
            "output": 128000
          },
          "options": {
            "store": false
          },
          "variants": {
            "low": {},
            "medium": {},
            "high": {}
          }
        },
        "gpt-5.1-codex-max": {
          "name": "GPT-5.1 Codex Max",
          "limit": {
            "context": 400000,
            "output": 128000
          },
          "options": {
            "store": false
          },
          "variants": {
            "low": {},
            "medium": {},
            "high": {}
          }
        },
        "gpt-5.1-codex-mini": {
          "name": "GPT-5.1 Codex Mini",
          "limit": {
            "context": 400000,
            "output": 128000
          },
          "options": {
            "store": false
          },
          "variants": {
            "low": {},
            "medium": {},
            "high": {}
          }
        },
        "gpt-5.2": {
          "name": "GPT-5.2",
          "limit": {
            "context": 400000,
            "output": 128000
          },
          "options": {
            "store": false
          },
          "variants": {
            "low": {},
            "medium": {},
            "high": {},
            "xhigh": {}
          }
        },
        "gpt-5.4": {
          "name": "GPT-5.4",
          "limit": {
            "context": 1050000,
            "output": 128000
          },
          "options": {
            "store": false
          },
          "variants": {
            "low": {},
            "medium": {},
            "high": {},
            "xhigh": {}
          }
        },
        "gpt-5.4-mini": {
          "name": "GPT-5.4 Mini",
          "limit": {
            "context": 400000,
            "output": 128000
          },
          "options": {
            "store": false
          },
          "variants": {
            "low": {},
            "medium": {},
            "high": {},
            "xhigh": {}
          }
        },
        "gpt-5.4-nano": {
          "name": "GPT-5.4 Nano",
          "limit": {
            "context": 400000,
            "output": 128000
          },
          "options": {
            "store": false
          },
          "variants": {
            "low": {},
            "medium": {},
            "high": {},
            "xhigh": {}
          }
        },
        "gpt-5.3-codex-spark": {
          "name": "GPT-5.3 Codex Spark",
          "limit": {
            "context": 128000,
            "output": 32000
          },
          "options": {
            "store": false
          },
          "variants": {
            "low": {},
            "medium": {},
            "high": {},
            "xhigh": {}
          }
        },
        "gpt-5.3-codex": {
          "name": "GPT-5.3 Codex",
          "limit": {
            "context": 400000,
            "output": 128000
          },
          "options": {
            "store": false
          },
          "variants": {
            "low": {},
            "medium": {},
            "high": {},
            "xhigh": {}
          }
        },
        "gpt-5.2-codex": {
          "name": "GPT-5.2 Codex",
          "limit": {
            "context": 400000,
            "output": 128000
          },
          "options": {
            "store": false
          },
          "variants": {
            "low": {},
            "medium": {},
            "high": {},
            "xhigh": {}
          }
        },
        "codex-mini-latest": {
          "name": "Codex Mini",
          "limit": {
            "context": 200000,
            "output": 100000
          },
          "options": {
            "store": false
          },
          "variants": {
            "low": {},
            "medium": {},
            "high": {}
          }
        }
      }
    }
  },
  "agent": {
    "build": {
      "options": {
        "store": false
      }
    },
    "plan": {
      "options": {
        "store": false
      }
    }
  },
  "$schema": "https://opencode.ai/config.json"
}
\`\`\`

你现在至少要确认这几件事：

1. \`baseURL\` 已经是 \`https://token.gepinkeji.com/v1\`
2. 你已经把 \`apiKey\` 替换成自己的真实密钥
3. \`gpt-5.4\` 已经在模型列表里
4. 这份配置使用的是默认 provider：\`openai\`

如果你不想把真实 Key 直接写在配置文件里，可以把 \`apiKey\` 那一行先删掉，保存配置后再用 \`/connect\` 录入。

---

## 步骤 3：开始使用 OpenCode

### 3.1 启动控制台

在项目目录里执行：

\`\`\`bash
opencode
\`\`\`

这时 OpenCode 会打开交互控制台。

![OpenCode 控制台截图](${assetMap["opencode-step-2.png"]})

### 3.2 如果你没有把 API Key 写进配置文件，就使用 \`/connect\`

在控制台里输入：

\`\`\`text
/connect
\`\`\`

![OpenCode connect 命令截图](${assetMap["opencode-step-3.png"]})

### 3.3 输入 Provider 名称

当它让你选择或输入 Provider 时，填：

\`\`\`text
openai
\`\`\`

![OpenCode 输入 provider 截图](${assetMap["opencode-step-4.png"]})

### 3.4 输入 API Key

接着把你的 API Key 粘贴进去，然后按回车。

![OpenCode 输入 API Key 截图](${assetMap["opencode-step-5.png"]})

### 3.5 开始对话

配置完成后，你就可以直接开始使用 \`GPT-5.4\` 了。

第一次建议先发一句最简单的话测试：

\`\`\`text
请只回复：OpenCode 已连接成功
\`\`\`

![OpenCode 使用效果截图](${assetMap["opencode-step-6.png"]})

---

## 常见问题

### 1. 执行 \`npm install -g opencode-ai\` 时提示找不到 npm

这通常说明 Node.js 还没有装好。

先看：

- [Node.js 安装教程](#doc-node-js)

### 2. 配置文件保存了，但还是连不上

重点检查：

- \`baseURL\` 是否写成了 \`https://token.gepinkeji.com/v1\`
- 模型名是否包含并正确填写了 \`gpt-5.4\`
- API Key 是否正确

### 3. \`/connect\` 之后还是报错

常见原因有这几种：

- 你输入的 Provider 名称不是 \`openai\`
- API Key 复制时多了空格
- 你的账号没有这个模型权限

### 4. 我到底该选“写进 JSON”还是“用 /connect”

建议这样选：

- 只在本机临时使用：可以直接写进 JSON，最省事
- 想让配置文件更干净：用 \`/connect\`

## 官方参考

- [OpenCode 官网](https://opencode.ai/)
- [OpenCode Intro](https://opencode.ai/docs/)
- [OpenCode Providers](https://opencode.ai/docs/providers)
- [OpenCode Config](https://opencode.ai/docs/config/)
- [Node.js 安装教程](#doc-node-js)`,
    isEntry: false,
    headings: [
      {
        "id": "doc-opencode-官方网站",
        "text": "官方网站",
        "level": 2
      },
      {
        "id": "doc-opencode-开始前你要准备什么",
        "text": "开始前你要准备什么",
        "level": 2
      },
      {
        "id": "doc-opencode-步骤-1-安装-opencode",
        "text": "步骤 1：安装 OpenCode",
        "level": 2
      },
      {
        "id": "doc-opencode-步骤-2-配置你的-openai-兼容接口",
        "text": "步骤 2：配置你的 OpenAI 兼容接口",
        "level": 2
      },
      {
        "id": "doc-opencode-2-1-配置文件放在哪里",
        "text": "2.1 配置文件放在哪里",
        "level": 3
      },
      {
        "id": "doc-opencode-2-2-先理解-provider-的用法",
        "text": "2.2 先理解 provider 的用法",
        "level": 3
      },
      {
        "id": "doc-opencode-2-3-配置-opencode-json-或-opencode-jsonc",
        "text": "2.3 配置 `opencode.json` 或 `opencode.jsonc`",
        "level": 3
      },
      {
        "id": "doc-opencode-步骤-3-开始使用-opencode",
        "text": "步骤 3：开始使用 OpenCode",
        "level": 2
      },
      {
        "id": "doc-opencode-3-1-启动控制台",
        "text": "3.1 启动控制台",
        "level": 3
      },
      {
        "id": "doc-opencode-3-2-如果你没有把-api-key-写进配置文件-就使用-connect",
        "text": "3.2 如果你没有把 API Key 写进配置文件，就使用 `/connect`",
        "level": 3
      },
      {
        "id": "doc-opencode-3-3-输入-provider-名称",
        "text": "3.3 输入 Provider 名称",
        "level": 3
      },
      {
        "id": "doc-opencode-3-4-输入-api-key",
        "text": "3.4 输入 API Key",
        "level": 3
      },
      {
        "id": "doc-opencode-3-5-开始对话",
        "text": "3.5 开始对话",
        "level": 3
      },
      {
        "id": "doc-opencode-常见问题",
        "text": "常见问题",
        "level": 2
      },
      {
        "id": "doc-opencode-1-执行-npm-install-g-opencode-ai-时提示找不到-npm",
        "text": "1. 执行 `npm install -g opencode-ai` 时提示找不到 npm",
        "level": 3
      },
      {
        "id": "doc-opencode-2-配置文件保存了-但还是连不上",
        "text": "2. 配置文件保存了，但还是连不上",
        "level": 3
      },
      {
        "id": "doc-opencode-3-connect-之后还是报错",
        "text": "3. `/connect` 之后还是报错",
        "level": 3
      },
      {
        "id": "doc-opencode-4-我到底该选-写进-json-还是-用-connect",
        "text": "4. 我到底该选“写进 JSON”还是“用 /connect”",
        "level": 3
      },
      {
        "id": "doc-opencode-官方参考",
        "text": "官方参考",
        "level": 2
      }
    ],
  },
  {
    id: "doc-openclaw",
    filename: "OpenClaw",
    title: "OpenClaw 接入 OpenAI 兼容 API 教程",
    summary: "覆盖 OpenClaw 向导式配置和 Custom Provider 接入。",
    markdown: `如果你的目标是“把第三方 OpenAI 兼容接口接到本地工具里”，OpenClaw 是比较适合新手的一种方式，因为它官方文档明确支持：

- 安装向导
- Onboarding 向导
- Custom Provider
- \`Base URL\`、\`API Key\`、\`Model ID\`

你开始前准备好：

- \`Base URL\`：这里填 \`https://token.gepinkeji.com/\`
- \`API Key\`：例如 \`sk-xxxx\`
- \`Model\`：例如 \`GPT-5.4\`

## 官方网站

- OpenClaw 官网：https://openclaw.ai/
- OpenClaw 文档：https://docs.openclaw.ai/
- OpenClaw 安装说明：https://docs.openclaw.ai/install
- Node.js 教程：[node.js.md](#doc-node-js)

## 推荐你记住的最简单流程

1. 安装 OpenClaw
2. 运行 \`openclaw onboard\`
3. 选择 \`Custom Provider\`
4. 选择 \`OpenAI-compatible\`
5. 输入 \`Base URL\`、\`API Key\`、\`Model ID\`
6. 打开控制面板测试

安装方式上，这篇文档统一优先使用 Node.js + \`npm\`，这样三端步骤最一致；官方安装脚本保留为备用方案。

## 如果安装脚本失败，先装 Node.js 再重试

如果你不想用 npm，或者 npm 安装失败，可以再改用官方安装脚本。大多数情况下你不需要手动研究更多依赖。

但如果你遇到下面这些问题：

- 安装脚本中途失败
- 终端提示缺少运行时
- \`openclaw\` 命令装完后不能正常启动

可以先补装 Node.js \`LTS\` 版本，再重新执行 OpenClaw 安装命令。

请先看：

- [Node.js 安装教程](#doc-node-js)

确认 \`node --version\` 和 \`npm --version\` 都能正常返回版本号后，再重新安装 OpenClaw。

---

## Windows

### 第 1 步：安装 OpenClaw

OpenClaw 官方说明，Windows 原生可用，但 \`WSL2\` 会更稳定。为了让步骤更统一，这篇文档优先使用 npm 安装。

打开 PowerShell，执行：

\`\`\`bash
npm install -g openclaw@latest
\`\`\`

安装完成后，执行：

\`\`\`powershell
openclaw --version
\`\`\`

如果能看到版本号，说明安装成功。

如果 npm 安装失败，再改用官方 PowerShell 安装脚本：

\`\`\`powershell
iwr -useb https://openclaw.ai/install.ps1 | iex
\`\`\`

### 第 2 步：运行初始化向导

\`\`\`powershell
openclaw onboard --install-daemon
\`\`\`

如果你不想装后台服务，也可以先用：

\`\`\`powershell
openclaw onboard
\`\`\`

### 第 3 步：在向导里选择自定义 Provider

当向导问你选哪个模型提供方时：

1. 选择 \`Custom Provider\`
2. 选择 \`OpenAI-compatible\`

然后按提示依次填写：

1. \`Base URL\`
2. \`API Key\`
3. \`Model ID\`
4. 可选别名

示例：

- \`Base URL\`：\`https://token.gepinkeji.com/\`
- \`API Key\`：\`sk-xxxx\`
- \`Model ID\`：\`GPT-5.4\`

### 第 4 步：打开控制面板测试

执行：

\`\`\`powershell
openclaw dashboard
\`\`\`

浏览器打开后，输入一句测试话术：

\`\`\`text
请只回复：OpenClaw Windows 接口已连接成功
\`\`\`

如果有正常回复，说明已经接通。

---

## macOS

### 第 1 步：安装 OpenClaw

打开终端，执行：

\`\`\`bash
npm install -g openclaw@latest
\`\`\`

安装完成后确认版本：

\`\`\`bash
openclaw --version
\`\`\`

如果 npm 安装失败，再改用官方安装脚本：

\`\`\`bash
curl -fsSL --proto '=https' --tlsv1.2 https://openclaw.ai/install.sh | bash
\`\`\`

### 第 2 步：运行初始化向导

\`\`\`bash
openclaw onboard --install-daemon
\`\`\`

### 第 3 步：选择 Custom Provider

在向导里：

1. 选择 \`Custom Provider\`
2. 选择 \`OpenAI-compatible\`
3. 输入你的 \`Base URL\`
4. 输入你的 \`API Key\`
5. 输入你的 \`Model ID\`

### 第 4 步：打开 Dashboard 测试

\`\`\`bash
openclaw dashboard
\`\`\`

如果浏览器能正常打开控制界面，再发一条简单消息测试即可。

---

## Linux

### 第 1 步：安装 OpenClaw

Linux 上这篇文档优先使用 npm 安装：

\`\`\`bash
npm install -g openclaw@latest
\`\`\`

如果你只是想改用官方安装脚本，也可以执行：

\`\`\`bash
curl -fsSL --proto '=https' --tlsv1.2 https://openclaw.ai/install.sh | bash
\`\`\`

安装后确认版本：

\`\`\`bash
openclaw --version
\`\`\`

### 第 2 步：运行向导

\`\`\`bash
openclaw onboard --install-daemon
\`\`\`

### 第 3 步：选择兼容模式

按向导一步一步填：

1. 选择 \`Custom Provider\`
2. 兼容模式选 \`OpenAI-compatible\`
3. 填 \`Base URL\`
4. 填 \`API Key\`
5. 填 \`Model ID\`

### 第 4 步：打开网页控制面板

\`\`\`bash
openclaw dashboard
\`\`\`

打开后测试一句：

\`\`\`text
请只回复：OpenClaw Linux 已连接成功
\`\`\`

---

## 如果向导没配成功，可以手动写配置

这部分不是必须，只是给你留个备用方案。

OpenClaw 官方文档也支持通过自定义 provider 配置 \`baseUrl\`。

示例思路如下：

\`\`\`json
{
  "models": {
    "providers": {
      "custom-proxy": {
        "baseUrl": "https://token.gepinkeji.com/",
        "apiKey": "你的API_KEY",
        "api": "openai-completions",
        "models": [
          {
            "id": "GPT-5.4",
            "name": "GPT-5.4",
            "reasoning": false,
            "input": ["text"]
          }
        ]
      }
    }
  }
}
\`\`\`

如果你是第一次接触 OpenClaw，建议先把向导跑通，再研究手动配置。

---

## 常见问题

### 1. Base URL 要不要带 \`/v1\`

大多数 OpenAI 兼容接口都需要。最稳妥的办法是直接看你服务商给你的示例地址。

### 2. 向导里没看到我要的服务商名字

没关系，直接选 \`Custom Provider\` 即可。

### 3. 为什么我接的是第三方接口，却要选 \`OpenAI-compatible\`

因为你接的不是“OpenAI 官方平台”，而是“兼容 OpenAI 接口格式”的服务。

### 4. 打开 dashboard 后没有回复

重点检查：

- \`Base URL\` 是否能在浏览器或终端访问
- \`API Key\` 是否正确
- \`Model ID\` 是否真实可用

## 官方参考

- [OpenClaw 官网](https://openclaw.ai/)
- [OpenClaw 文档](https://docs.openclaw.ai/)
- [OpenClaw Getting Started](https://docs.openclaw.ai/start/getting-started)
- [OpenClaw Onboarding Overview](https://docs.openclaw.ai/start/onboarding-overview)
- [OpenClaw Install](https://docs.openclaw.ai/install)
- [OpenClaw Installer Internals](https://docs.openclaw.ai/install/installer)
- [OpenClaw OpenAI Provider](https://docs.openclaw.ai/providers/openai)
- [OpenClaw Configuration Reference](https://docs.openclaw.ai/gateway/configuration-reference)
- [Node.js 安装教程](#doc-node-js)`,
    isEntry: false,
    headings: [
      {
        "id": "doc-openclaw-官方网站",
        "text": "官方网站",
        "level": 2
      },
      {
        "id": "doc-openclaw-推荐你记住的最简单流程",
        "text": "推荐你记住的最简单流程",
        "level": 2
      },
      {
        "id": "doc-openclaw-如果安装脚本失败-先装-node-js-再重试",
        "text": "如果安装脚本失败，先装 Node.js 再重试",
        "level": 2
      },
      {
        "id": "doc-openclaw-windows",
        "text": "Windows",
        "level": 2
      },
      {
        "id": "doc-openclaw-第-1-步-安装-openclaw",
        "text": "第 1 步：安装 OpenClaw",
        "level": 3
      },
      {
        "id": "doc-openclaw-第-2-步-运行初始化向导",
        "text": "第 2 步：运行初始化向导",
        "level": 3
      },
      {
        "id": "doc-openclaw-第-3-步-在向导里选择自定义-provider",
        "text": "第 3 步：在向导里选择自定义 Provider",
        "level": 3
      },
      {
        "id": "doc-openclaw-第-4-步-打开控制面板测试",
        "text": "第 4 步：打开控制面板测试",
        "level": 3
      },
      {
        "id": "doc-openclaw-macos",
        "text": "macOS",
        "level": 2
      },
      {
        "id": "doc-openclaw-第-1-步-安装-openclaw-2",
        "text": "第 1 步：安装 OpenClaw",
        "level": 3
      },
      {
        "id": "doc-openclaw-第-2-步-运行初始化向导-2",
        "text": "第 2 步：运行初始化向导",
        "level": 3
      },
      {
        "id": "doc-openclaw-第-3-步-选择-custom-provider",
        "text": "第 3 步：选择 Custom Provider",
        "level": 3
      },
      {
        "id": "doc-openclaw-第-4-步-打开-dashboard-测试",
        "text": "第 4 步：打开 Dashboard 测试",
        "level": 3
      },
      {
        "id": "doc-openclaw-linux",
        "text": "Linux",
        "level": 2
      },
      {
        "id": "doc-openclaw-第-1-步-安装-openclaw-3",
        "text": "第 1 步：安装 OpenClaw",
        "level": 3
      },
      {
        "id": "doc-openclaw-第-2-步-运行向导",
        "text": "第 2 步：运行向导",
        "level": 3
      },
      {
        "id": "doc-openclaw-第-3-步-选择兼容模式",
        "text": "第 3 步：选择兼容模式",
        "level": 3
      },
      {
        "id": "doc-openclaw-第-4-步-打开网页控制面板",
        "text": "第 4 步：打开网页控制面板",
        "level": 3
      },
      {
        "id": "doc-openclaw-如果向导没配成功-可以手动写配置",
        "text": "如果向导没配成功，可以手动写配置",
        "level": 2
      },
      {
        "id": "doc-openclaw-常见问题",
        "text": "常见问题",
        "level": 2
      },
      {
        "id": "doc-openclaw-1-base-url-要不要带-v1",
        "text": "1. Base URL 要不要带 `/v1`",
        "level": 3
      },
      {
        "id": "doc-openclaw-2-向导里没看到我要的服务商名字",
        "text": "2. 向导里没看到我要的服务商名字",
        "level": 3
      },
      {
        "id": "doc-openclaw-3-为什么我接的是第三方接口-却要选-openai-compatible",
        "text": "3. 为什么我接的是第三方接口，却要选 `OpenAI-compatible`",
        "level": 3
      },
      {
        "id": "doc-openclaw-4-打开-dashboard-后没有回复",
        "text": "4. 打开 dashboard 后没有回复",
        "level": 3
      },
      {
        "id": "doc-openclaw-官方参考",
        "text": "官方参考",
        "level": 2
      }
    ],
  },
  {
    id: "doc-curso",
    filename: "Curso",
    title: "Cursor 接入 OpenAI 兼容 API 教程 默认以会科学上网",
    summary: "覆盖 Cursor 的公开入口检查与自定义地址判断流程。",
    markdown: `你开始前先准备好：

- \`Base URL\`：这里填 \`https://token.gepinkeji.com/\`
- \`API Key\`：例如 \`sk-xxxx\`
- \`Model\`：例如 \`GPT-5.4\`

## 官方网站

- Cursor 官网：https://cursor.com/
- Cursor 下载页：https://cursor.com/en-US/download
- Cursor 文档：https://docs.cursor.com/

## 先看最重要的说明

Cursor 官方文档明确支持：

- 在 \`Cursor Settings > Models\` 中填写 API Key
- 使用 OpenAI、Anthropic、Google、Azure OpenAI、AWS Bedrock

但截至目前公开官方文档中，没有把“第三方 OpenAI 兼容网关的自定义 Base URL”单独写成一份完整说明。

所以这篇教程我会这样写：

1. 先按官方文档教你完成安装和 API Key 配置
2. 再教你在当前版本里查找 \`Base URL\` / \`OpenAI URL\` / \`Override OpenAI Base URL\` 这类字段
3. 如果你的版本没有这个字段，我会明确告诉你这时该怎么办

## 使用前你要知道

Cursor 官方还特别说明了两点：

1. 自定义 API Key 只适用于标准聊天模型
2. 像 Tab Completion 这类依赖 Cursor 专有模型的功能，不一定走你自己的 Key

所以你接入成功后，建议优先用聊天窗口做测试，不要先拿自动补全来判断成败。

### 第 1 步：下载 安装包 macos 为例子

到官方下载安装页下载 版本并安装：

- 下载地址：https://cursor.com/en-US/download
- 如果你是公司电脑、希望给所有用户统一安装，也可以选系统级安装包
![alt text](${assetMap["image-10.png"]})

下载完成后：

1. 吧macos 推拽到app中
![alt text](${assetMap["image-11.png"]})
2. 按默认选项继续安装
3. 安装完成后打开 Cursor
4. 登陆 
![alt text](${assetMap["image-12.png"]})
![alt text](${assetMap["image-13.png"]})

### 第 2 步：完成首次启动

第一次打开时，按提示完成这些基础设置：

1. 选择键位风格
2. 选择主题
3. 完成初始化

这一步和接口接入无关，直接按默认走也可以。

### 第 3 步：打开模型设置页


### 第 5 步：查找 Base URL 相关字段

![alt text](${assetMap["image-14.png"]})
继续在同一页找这些名字相近的字段：

- \`Base URL\`
- \`OpenAI Base URL\`
- \`OpenAI URL\`
- \`Override OpenAI Base URL\`

如果你看到了其中任意一个：

1. 把它改成你的 \`Base URL\`
2. 保存设置
3. 重新打开一个新聊天窗口
4. 选择一个标准聊天模型

如果你没有看到类似字段：

- 说明你当前版本公开可见的设置里，至少没有暴露出第三方 OpenAI 兼容地址入口
- 这时按官方文档，Cursor 至少能保证“自带 OpenAI API Key”接入
- 如果你必须使用第三方 OpenAI 兼容网关，建议优先改用 [OpenCode.md](#doc-opencode) 或 [OpenClaw.md](#doc-openclaw)

### 第 6 步：测试是否接通

新建一个聊天窗口，发送：

\`\`\`text
请只回复：Cursor 已连接成功
\`\`\`
![alt text](${assetMap["image-15.png"]})
如果能返回正常内容，说明聊天模型已经可用。

## 常见问题

### 1. 已经填了 API Key，但还是不走我的接口

可能原因：

- 你的版本没有开放 \`Base URL\` 设置
- 你测试的是专有功能，而不是普通聊天模型

### 2. 为什么 Verify 通过了，但聊天还是报错

常见原因：

- 你选了不被自定义 Key 支持的模型
- 你的兼容网关不支持 Cursor 当前发出的参数

### 3. Cursor 会不会把 Key 发到自己的服务器

根据 Cursor 官方 API Key 文档，API Key 不会被保存，但请求会经过他们的后端完成最终 prompt 组装。

## 官方参考

- [Cursor 官网](https://cursor.com/)
- [Cursor Installation](https://docs.cursor.com/get-started/installation)
- [Cursor Download](https://cursor.com/en-US/download)
- [Cursor API Keys](https://docs.cursor.com/advanced/api-keys)`,
    isEntry: false,
    headings: [
      {
        "id": "doc-curso-官方网站",
        "text": "官方网站",
        "level": 2
      },
      {
        "id": "doc-curso-先看最重要的说明",
        "text": "先看最重要的说明",
        "level": 2
      },
      {
        "id": "doc-curso-使用前你要知道",
        "text": "使用前你要知道",
        "level": 2
      },
      {
        "id": "doc-curso-第-1-步-下载-安装包-macos-为例子",
        "text": "第 1 步：下载 安装包 macos 为例子",
        "level": 3
      },
      {
        "id": "doc-curso-第-2-步-完成首次启动",
        "text": "第 2 步：完成首次启动",
        "level": 3
      },
      {
        "id": "doc-curso-第-3-步-打开模型设置页",
        "text": "第 3 步：打开模型设置页",
        "level": 3
      },
      {
        "id": "doc-curso-第-5-步-查找-base-url-相关字段",
        "text": "第 5 步：查找 Base URL 相关字段",
        "level": 3
      },
      {
        "id": "doc-curso-第-6-步-测试是否接通",
        "text": "第 6 步：测试是否接通",
        "level": 3
      },
      {
        "id": "doc-curso-常见问题",
        "text": "常见问题",
        "level": 2
      },
      {
        "id": "doc-curso-1-已经填了-api-key-但还是不走我的接口",
        "text": "1. 已经填了 API Key，但还是不走我的接口",
        "level": 3
      },
      {
        "id": "doc-curso-2-为什么-verify-通过了-但聊天还是报错",
        "text": "2. 为什么 Verify 通过了，但聊天还是报错",
        "level": 3
      },
      {
        "id": "doc-curso-3-cursor-会不会把-key-发到自己的服务器",
        "text": "3. Cursor 会不会把 Key 发到自己的服务器",
        "level": 3
      },
      {
        "id": "doc-curso-官方参考",
        "text": "官方参考",
        "level": 2
      }
    ],
  },
  {
    id: "doc-trae",
    filename: "Trae",
    title: "Trae 接入我们中转站 API 教程",
    summary: "覆盖 Trae 的公开支持边界、入口检查与止损判断。",
    markdown: `这篇教程是写给第一次接触接口配置的新手的。

先把最重要的话放前面：

- 截至 \`2026-04-15\`，Trae 官方公开文档能确认的内容主要是安装、首次启动、登录和基础 AI 设置。
- 截至 \`2026-04-15\`，我没有在 Trae 官方公开文档里找到一条可以稳定复现的“第三方 OpenAI 兼容 \`Base URL + API Key + Model\`”标准接入路径。
- 所以这篇教程不会硬编一个看起来很像真的菜单路径，而是教你怎么自己判断“当前版本能不能接”，这样最不容易白折腾。

如果你只想先看结论：

1. 先准备好 \`Base URL\`、\`API Key\`、\`Model\`
2. 打开 Trae，进入设置里找 \`AI\`、\`Models\`、\`Provider\`、\`Custom Model\`、\`OpenAI Compatible\`
3. 如果看到了自定义接口输入框，就按本文填写并测试
4. 如果根本看不到相关入口，就先停下，不要反复乱试

## 先准备好 3 个信息

你开始前，至少要准备下面这 3 个值：

| 你要填的内容 | 这是什么意思 | 示例 |
| --- | --- | --- |
| \`Base URL\` | 接口地址，不是官网首页地址 | \`https://token.gepinkeji.com/v1\` |
| \`API Key\` | 你的密钥，通常以 \`sk-\` 开头 | \`sk-xxxx\` |
| \`Model\` | 你要调用的模型名 | \`GPT-5.4\` |

最容易填错的是 \`Base URL\`。

你要记住：

- \`Base URL\` 填接口地址，不要填官网首页
- 如果你的后台已经给了你完整接口地址，就以后台显示为准
- 如果你拿到的是标准 OpenAI 兼容地址，通常会带 \`/v1\`

![接入前需要准备的信息](${assetMap["trae-prep-card.svg"]})

### 你可以直接照着填这份模板

\`\`\`text
Base URL:
https://token.gepinkeji.com/v1

API Key:
sk-请替换成你自己的真实密钥

Model:
GPT-5.4
\`\`\`

## 这 3 个值一般去哪里拿

如果你接的是我们自己的中转站，可以先按这条最短路径找：

1. 登录 GPAPI 控制台
2. 进入左侧菜单 \`API 密钥\`
3. 如果你还没有密钥，点击 \`创建密钥\`
4. 创建成功后，立即复制形如 \`sk-xxxx\` 的完整密钥
5. 还在 \`API 密钥\` 页面里查看或复制 \`API 端点\`

对新手来说，可以先这样理解：

- \`API Key\` 就在 \`API 密钥\` 页面生成
- \`Base URL\` 优先用 \`API 密钥\` 页面展示的 \`API 端点\`
- \`Model\` 不要自己猜，优先复制后台给你的准确模型名

### 如果你拿不到 \`Model\`，先这样确认

你可以按这个顺序确认模型名：

1. 先看中转站后台有没有 \`模型列表\`、\`允许模型\`、\`可用模型\`
2. 如果你拿到的是套餐说明或客服给你的模型名，直接复制原文
3. 如果只看到了展示名称，不确定真实调用名，就不要自己改写

最稳妥的做法是：

- 后台写什么模型名，你就填什么
- 不确定时，把 \`GPT-5.4\` 当示例，不要当成所有账号都一定可用的固定值
- 如果保存后提示模型不存在或无权限，优先怀疑模型名或分组权限，不要先怀疑 Trae

## 官方链接

- Trae 官网：https://traeide.com/
- Trae 文档：https://traeide.com/docs
- Trae 中文文档：https://traeide.com/zh/docs
- Trae 安装说明：https://traeide.com/docs/how-to-setup-trae

## 先理解这篇教程在教你什么

这篇教程不是在保证“任何版本的 Trae 都一定能接第三方接口”。

这篇教程真正帮你完成的是两件事：

1. 如果你当前版本支持自定义 OpenAI 兼容接口，你能顺着步骤把它配好
2. 如果你当前版本没有这个入口，你能很快确认“不支持”，而不是在错误的页面里反复找半天

## 第 1 步：安装并打开 Trae

### Windows

1. 进入 Trae 官网下载 Windows 版本
2. 双击安装包
3. 按默认选项安装
4. 安装完成后打开 Trae

### macOS

1. 进入 Trae 官网下载 macOS 版本
2. 打开安装包
3. 把 Trae 拖到 \`Applications\`
4. 第一次打开时按系统提示允许启动

### Linux

截至 \`2026-04-15\`，Trae 官网 FAQ 公开说明里仍以 Windows 和 macOS 为主，Linux 不属于这篇教程的稳定接入范围。

如果你必须在 Linux 上走第三方 OpenAI 兼容接口，建议优先改用：

- [OpenCode.md](#doc-opencode)
- [OpenClaw.md](#doc-openclaw)

## 第 2 步：完成首次启动和登录

第一次打开 Trae 时，通常会先让你完成这些基础设置：

1. 选择主题
2. 选择语言
3. 按需导入 VS Code 或 Cursor 配置
4. 登录 Trae 账号

这一段先正常完成就行，不用急着找接口设置。

如果你还没登录，建议先登录再继续，因为很多 AI 相关入口只有登录后才会显示。

## 第 3 步：去设置里找“能不能接第三方接口”的入口

这是整篇教程最关键的一步。

请你打开 Trae 后，优先按这个顺序找：

1. 右上角个人资料图标
2. \`Settings\`
3. 左侧导航里的 \`Trae AI\`
4. 再继续看有没有 \`Models\`、\`Provider\`、\`Custom Model\`

如果你没在上面这条路径里找到，也可以再顺手检查：

1. 左下角设置按钮
2. 设置页顶部搜索框里输入 \`AI\`
3. 设置页顶部搜索框里输入 \`Model\`
4. 设置页顶部搜索框里输入 \`Provider\`

如果你的设置页没有搜索框，就直接按左侧导航一项项看，不要切到系统搜索，也不用去系统文件里找。

如果你看到下面这些词，说明你已经找对方向了：

- \`AI\`
- \`Models\`
- \`Provider\`
- \`Custom Model\`
- \`Custom Provider\`
- \`API\`
- \`OpenAI Compatible\`
- \`OpenAI-Compatible\`

![Trae 里优先检查的设置入口](${assetMap["trae-settings-checklist.svg"]})

根据 Trae 官方当前公开的 AI 设置说明，你大概率至少会看到与 AI 聊天语言、代码索引、快捷键相关的设置。

如果公开可见的设置页里只有这些内容，却没有 \`Base URL\`、\`API Key\`、\`Model\` 之类的输入框，也可以把它当成一个明显信号：

\`当前公开文档对应的设置页，并没有展示标准第三方 OpenAI 兼容接口入口。\`

### 什么情况叫“真的找到入口了”

只有当你看到了下面这些输入框中的至少 2 到 3 个时，才算真的找到了可配置入口：

- \`Base URL\`
- \`API Key\`
- \`Model\`
- \`Endpoint\`
- \`Provider\`

如果你只是看到了“切换模型”或者“选择官方内置模型”的下拉框，这还不算。

## 第 4 步：如果你找到了自定义接口入口，就这样填

如果你已经看到了 \`Base URL\`、\`API Key\`、\`Model\` 这样的输入框，直接按下面填写：

| 字段 | 建议填写 |
| --- | --- |
| \`Base URL\` | \`https://token.gepinkeji.com/v1\` |
| \`API Key\` | 你的真实密钥 |
| \`Model\` | \`GPT-5.4\` |

填写顺序建议这样走：

1. 先填 \`Base URL\`
2. 再填 \`API Key\`
3. 最后填 \`Model\`
4. 点击保存
5. 新建一个最简单的聊天测试

### 测试话术直接复制这一句

\`\`\`text
请只回复：Trae 已连接成功
\`\`\`

如果你能收到正常回复，说明至少当前这组配置已经能发起请求。

如果你不确定 Trae 有没有真的保存成功，可以再做一次最简单的确认：

1. 先离开当前设置页
2. 再重新进入刚才的配置页
3. 看你填的 \`Base URL\`、\`API Key\`、\`Model\` 是否还在

如果这些值已经丢了，优先说明你还没有真正保存成功。

再补一个很重要的确认动作：

1. 回到 Trae 当前正在使用的 AI 或模型页面
2. 看当前选中的 Provider 或 Model，是不是你刚才保存的那一组
3. 如果页面里仍然只显示 Trae 内置模型，而没有你刚配置的自定义项，就先不要急着测

你可以把这句话记住：

\`保存成功\` 不等于 \`当前会话已经切到你刚配置的 Provider\`。

## 第 5 步：如果你没找到入口，就不要继续硬试

这一点对新手非常重要。

如果你已经认真检查过设置页，但还是没有看到 \`Base URL\`、\`API Key\`、\`Model\` 之类的输入框，请直接把结论定为：

\`你当前看到的公开可用界面里，没有标准的第三方 OpenAI 兼容接口入口。\`

这时候最稳妥的做法不是继续乱点，而是二选一：

1. 继续使用 Trae 当前内置能力
2. 改用更明确支持自定义接口的工具

![能接和不能接时的判断流程](${assetMap["trae-decision-flow.svg"]})

更适合直接接第三方接口的替代方案：

- [OpenCode.md](#doc-opencode)
- [OpenClaw.md](#doc-openclaw)

## 常见错误

### 1. 把官网地址当成接口地址

错误示例：

\`\`\`text
https://traeide.com/
\`\`\`

这不是你的中转接口地址，不能填在 \`Base URL\` 里。

### 2. 把模型展示名当成真实模型名

有些后台会显示“GPT-5.4 高级版”这种展示名字，但真正要填的可能是 \`GPT-5.4\`。

如果填错，常见结果是：

- 保存成功但调用失败
- 提示模型不存在
- 提示没有权限

### 3. 少写了 \`/v1\`

如果你的接口是标准 OpenAI 兼容地址，但你只填了主域名，没有填 \`/v1\`，就可能请求失败。

最简单的判断方式：

- 以你后台展示的完整接口地址为准
- 如果没有单独说明，优先先试 \`https://token.gepinkeji.com/v1\`

### 4. 还没登录就开始找 API 设置

有些 AI 相关入口登录前不会显示。

所以正确顺序是：

1. 先安装
2. 再登录
3. 再看有没有模型或 Provider 设置

## 如果测试失败，先按这个顺序排查

### 情况 1：根本保存不了

先检查：

1. 有没有漏填必填项
2. \`API Key\` 是否复制完整
3. \`Base URL\` 是否误填成官网首页

### 情况 2：保存了，但发消息没有回复

先检查：

1. Trae 当前是不是还在使用你刚保存的 Provider
2. \`Base URL\` 是否应该带 \`/v1\`
3. 当前网络能不能访问你的接口地址

如果你用的是我们的 GPAPI 控制台，可以回到 \`API 密钥\` 页面做两件事：

1. 看 \`API 端点\` 是否和你填进 Trae 的地址一致
2. 如果页面上有 \`测速\`，先点一下测速，确认这个地址本身能连通

### 情况 3：提示模型不存在

先检查：

1. 模型名是不是完全照后台复制
2. 有没有把展示名称当成真实模型名
3. 当前 Key 所在分组是否允许这个模型

### 情况 4：提示无权限或鉴权失败

先检查：

1. \`API Key\` 是否多复制了空格
2. 这个 Key 是否已禁用、过期或没有分组
3. 这个 Key 是否有可用额度

如果你不知道去哪里看这些信息，就回到 GPAPI 控制台的 \`API 密钥\` 页面，重点看这一行：

- \`状态\`
- \`分组\`
- \`额度\`
- \`今日 / 近30天用量\`

如果这个 Key 没有分组，或者状态不是启用中，就算 Trae 填对了也可能调不通。

### 情况 5：你完全找不到相关设置

这时不要继续硬试，直接回到本文第 5 步，把结论定为：

\`当前公开界面没有标准第三方 OpenAI 兼容接口入口。\``,
    isEntry: false,
    headings: [
      {
        "id": "doc-trae-先准备好-3-个信息",
        "text": "先准备好 3 个信息",
        "level": 2
      },
      {
        "id": "doc-trae-你可以直接照着填这份模板",
        "text": "你可以直接照着填这份模板",
        "level": 3
      },
      {
        "id": "doc-trae-这-3-个值一般去哪里拿",
        "text": "这 3 个值一般去哪里拿",
        "level": 2
      },
      {
        "id": "doc-trae-如果你拿不到-model-先这样确认",
        "text": "如果你拿不到 `Model`，先这样确认",
        "level": 3
      },
      {
        "id": "doc-trae-官方链接",
        "text": "官方链接",
        "level": 2
      },
      {
        "id": "doc-trae-先理解这篇教程在教你什么",
        "text": "先理解这篇教程在教你什么",
        "level": 2
      },
      {
        "id": "doc-trae-第-1-步-安装并打开-trae",
        "text": "第 1 步：安装并打开 Trae",
        "level": 2
      },
      {
        "id": "doc-trae-windows",
        "text": "Windows",
        "level": 3
      },
      {
        "id": "doc-trae-macos",
        "text": "macOS",
        "level": 3
      },
      {
        "id": "doc-trae-linux",
        "text": "Linux",
        "level": 3
      },
      {
        "id": "doc-trae-第-2-步-完成首次启动和登录",
        "text": "第 2 步：完成首次启动和登录",
        "level": 2
      },
      {
        "id": "doc-trae-第-3-步-去设置里找-能不能接第三方接口-的入口",
        "text": "第 3 步：去设置里找“能不能接第三方接口”的入口",
        "level": 2
      },
      {
        "id": "doc-trae-什么情况叫-真的找到入口了",
        "text": "什么情况叫“真的找到入口了”",
        "level": 3
      },
      {
        "id": "doc-trae-第-4-步-如果你找到了自定义接口入口-就这样填",
        "text": "第 4 步：如果你找到了自定义接口入口，就这样填",
        "level": 2
      },
      {
        "id": "doc-trae-测试话术直接复制这一句",
        "text": "测试话术直接复制这一句",
        "level": 3
      },
      {
        "id": "doc-trae-第-5-步-如果你没找到入口-就不要继续硬试",
        "text": "第 5 步：如果你没找到入口，就不要继续硬试",
        "level": 2
      },
      {
        "id": "doc-trae-常见错误",
        "text": "常见错误",
        "level": 2
      },
      {
        "id": "doc-trae-1-把官网地址当成接口地址",
        "text": "1. 把官网地址当成接口地址",
        "level": 3
      },
      {
        "id": "doc-trae-2-把模型展示名当成真实模型名",
        "text": "2. 把模型展示名当成真实模型名",
        "level": 3
      },
      {
        "id": "doc-trae-3-少写了-v1",
        "text": "3. 少写了 `/v1`",
        "level": 3
      },
      {
        "id": "doc-trae-4-还没登录就开始找-api-设置",
        "text": "4. 还没登录就开始找 API 设置",
        "level": 3
      },
      {
        "id": "doc-trae-如果测试失败-先按这个顺序排查",
        "text": "如果测试失败，先按这个顺序排查",
        "level": 2
      },
      {
        "id": "doc-trae-情况-1-根本保存不了",
        "text": "情况 1：根本保存不了",
        "level": 3
      },
      {
        "id": "doc-trae-情况-2-保存了-但发消息没有回复",
        "text": "情况 2：保存了，但发消息没有回复",
        "level": 3
      },
      {
        "id": "doc-trae-情况-3-提示模型不存在",
        "text": "情况 3：提示模型不存在",
        "level": 3
      },
      {
        "id": "doc-trae-情况-4-提示无权限或鉴权失败",
        "text": "情况 4：提示无权限或鉴权失败",
        "level": 3
      },
      {
        "id": "doc-trae-情况-5-你完全找不到相关设置",
        "text": "情况 5：你完全找不到相关设置",
        "level": 3
      }
    ],
  },
  {
    id: "doc-node-js",
    filename: "node.js",
    title: "Node.js 安装教程",
    summary: "覆盖 Node.js 运行环境安装，供依赖 npm 的客户端先补环境。",
    markdown: `这篇文档专门给第一次接触 Node.js 的同学准备。

如果你在其他接入文档里看到：

- \`npm install -g ...\`
- \`node --version\`
- \`npm --version\`

那就说明你需要先把 Node.js 装好，再继续后面的步骤。

## 官方网站

- Node.js 官网：https://nodejs.org/
- Node.js 下载页：https://nodejs.org/en/download
- Node.js Linux 包管理器说明：https://nodejs.org/en/download/package-manager

## 安装完成后怎么验证

无论你用什么系统，安装完成后打开终端，执行：

\`\`\`bash
node --version
npm --version
\`\`\`

如果都能显示版本号，说明 Node.js 已经安装成功。

建议新手优先安装 \`LTS\` 版本。

---

## Windows

### 第 1 步：打开下载页

进入：

\`\`\`text
https://nodejs.org/zh-cn/download
\`\`\`

### 第 2 步：下载 LTS 版本

建议优先下载：

- \`Windows Installer (.msi)\`

### 第 3 步：安装

双击安装包，然后：

1. 点击 \`Next\`
2. 接受协议
3. 保持默认选项
4. 点击 \`Install\`
5. 安装完成后关闭安装窗口

### 第 4 步：重新打开 PowerShell

把旧终端关掉，再打开一个新的 PowerShell 窗口。

### 第 5 步：验证

\`\`\`bash
node --version
npm --version
\`\`\`

### 常见问题

#### 1. 提示 \`node 不是内部或外部命令\`

先关闭终端，再打开一个新窗口重新测试。

如果还是不行，重新安装一次 Node.js，并保持默认选项。

---

## macOS

### 方式 A：官网下载包安装

这是最适合小白的方式。

#### 第 1 步：打开下载页

进入：

\`\`\`text
https://nodejs.org/zh-cn/download
\`\`\`
![alt text](${assetMap["image.png"]})
#### 第 2 步：下载 LTS 版本

如果你是：

- Apple 芯片 Mac：优先选择 Apple Silicon 对应安装包
- Intel Mac：选择 x64 安装包

#### 第 3 步：双击安装

按安装向导完成即可。
 ![alt text](${assetMap["image-1.png"]})

#### 第 4 步：验证
 - 打开终端
 ![alt text](${assetMap["image-2.png"]})
\`\`\`bash
node --version
npm --version
\`\`\`

### 方式 B：用 Homebrew 安装

如果你已经装了 Homebrew，也可以执行：

\`\`\`bash
brew install node
\`\`\`

然后执行：

\`\`\`bash
node --version
npm --version
\`\`\`

---

## Linux

Linux 最稳妥的办法是先看官方包管理器说明：

\`\`\`text
https://nodejs.org/en/download/package-manager
\`\`\`

### Ubuntu / Debian

可以先执行：

\`\`\`bash
sudo apt update
sudo apt install -y nodejs npm
\`\`\`
![alt text](${assetMap["image-3.png"]})

然后执行：

\`\`\`bash
node --version
npm --version
\`\`\`

### Arch Linux

可以执行：

\`\`\`bash
sudo pacman -S nodejs npm
\`\`\`

然后执行：

\`\`\`bash
node --version
npm --version
\`\`\`
![alt text](${assetMap["image-4.png"]})
### 常见问题

#### 1. 版本太旧

如果后续安装工具时报 Node.js 版本不够，就回到官方包管理器说明页，按官方方式升级到更高版本。

#### 2. 提示权限不足

先不要急着乱加 \`sudo\`，先确认 Node.js 和 npm 已经正常可用。`,
    isEntry: false,
    headings: [
      {
        "id": "doc-node-js-官方网站",
        "text": "官方网站",
        "level": 2
      },
      {
        "id": "doc-node-js-安装完成后怎么验证",
        "text": "安装完成后怎么验证",
        "level": 2
      },
      {
        "id": "doc-node-js-windows",
        "text": "Windows",
        "level": 2
      },
      {
        "id": "doc-node-js-第-1-步-打开下载页",
        "text": "第 1 步：打开下载页",
        "level": 3
      },
      {
        "id": "doc-node-js-第-2-步-下载-lts-版本",
        "text": "第 2 步：下载 LTS 版本",
        "level": 3
      },
      {
        "id": "doc-node-js-第-3-步-安装",
        "text": "第 3 步：安装",
        "level": 3
      },
      {
        "id": "doc-node-js-第-4-步-重新打开-powershell",
        "text": "第 4 步：重新打开 PowerShell",
        "level": 3
      },
      {
        "id": "doc-node-js-第-5-步-验证",
        "text": "第 5 步：验证",
        "level": 3
      },
      {
        "id": "doc-node-js-常见问题",
        "text": "常见问题",
        "level": 3
      },
      {
        "id": "doc-node-js-macos",
        "text": "macOS",
        "level": 2
      },
      {
        "id": "doc-node-js-方式-a-官网下载包安装",
        "text": "方式 A：官网下载包安装",
        "level": 3
      },
      {
        "id": "doc-node-js-方式-b-用-homebrew-安装",
        "text": "方式 B：用 Homebrew 安装",
        "level": 3
      },
      {
        "id": "doc-node-js-linux",
        "text": "Linux",
        "level": 2
      },
      {
        "id": "doc-node-js-ubuntu-debian",
        "text": "Ubuntu / Debian",
        "level": 3
      },
      {
        "id": "doc-node-js-arch-linux",
        "text": "Arch Linux",
        "level": 3
      },
      {
        "id": "doc-node-js-常见问题-2",
        "text": "常见问题",
        "level": 3
      }
    ],
  },
]
